homeworks
MDAUBEITEMANYA/Homework pull request #1
Opened 2022-01-30 07:43 UTC by MDAUBEITEMANYA

2022-02-04 12:47 UTC, p-kachalov requested changes

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +        for word in tpm_line:
https://docs.python.org/3/library/array.html#array.array.extend

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +    word_list = tuple(word_list)
why do you need a tuple?

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +    my_file = open(filepath, "r")
forget to close the file
that's why the context manager useful

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +        tpm_line = line.lower().replace('\n', '').split(',')
https://docs.python.org/3/library/stdtypes.html#str.strip

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +    for w in sorted_keys:
you can use enumerate instead of counter
but actually - this loop is not needed because you should return only names

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +def line_prepender(filename, line):
this function does not seem to be used

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +def get_top_performers_scv(file_path, number_of_top_students):
function name does not match its content

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +    # line_prepender('students.csv', 'student name,age,average mark')
it's a bad practice to leave commented code

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +def prev_res(func):
not the best name for a decorator

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +    with open('output.txt', "a") as f:
you don't need a file to store previous results
store it in the closure context

and why append mode if you only read?

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +            prev_output = f.readlines()
for empty file it returns empty list, exception will not be raised

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +            if filecmp.cmp(dir + '/' + str(dir_files[x]), dir + '/' + str(dir_files[i]), shallow=True):
https://docs.python.org/3/library/os.path.html

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +    for x in range(files_length):
usually, it's i, j, k for iter variables

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +    memo = {}
why do you need dict if you only store one value?

2022-02-04 12:47 UTC, p-kachalov commented on interview/four.py
> +    def wrapper(*args):
it would be nice not to forget **kwargs too

2022-02-07 11:47 UTC, MDAUBEITEMANYA commented on interview/four.py
> +def line_prepender(filename, line):
I use it to refactor csv file to work with it from example

2022-02-07 12:32 UTC, MDAUBEITEMANYA commented on interview/four.py
> +def most_common_words(filepath, number_of_words):
I split them and did everything lower. Isn't it right?

2022-02-08 11:00 UTC, p-kachalov approved these changes

2022-02-10 12:47 UTC, p-kachalov requested changes

2022-02-10 12:47 UTC, p-kachalov commented on interview/five.py
> +class FlyingBird(Bird):
ration doesn't have a default value
if you'll try to create this bird without specifying ration - it will raise an error

2022-02-10 12:47 UTC, p-kachalov commented on interview/five.py
> +        self.array = np.random.randint(10, size=(2, 3))
it will always generate 2x3 matrix

2022-02-10 12:47 UTC, p-kachalov commented on interview/five.py
> +        if self.cols != matrix.cols and self.rows != matrix.rows:
I think there should be `or` instead of `and`

2022-02-10 12:47 UTC, p-kachalov commented on interview/five.py
> +    @property
in this task you need to write your own implementation of @property decorator

2022-02-10 12:47 UTC, p-kachalov commented on interview/five.py
> +class HistoryDict:
have a look at https://docs.python.org/3/library/collections.html#collections.deque

2025-05-28 13:07 UTC, closed without merging